local t = require("tests.harness")
local bc = require("plugins.vscode-theme.better_comments")

t.suite("better_comments", function()
    t.test("a bare leader decodes with no flags", function()
        local parts = bc._parse_format_comments(":--")
        t.eq(#parts, 1)
        t.eq(parts[1].leader, "--")
        t.eq(parts[1].raw_flags, "")
    end)

    t.test("the three-part C style decodes start, middle and end", function()
        local parts = bc._parse_format_comments("s1:/*,mb:*,ex:*/")
        t.eq(#parts, 3)
        t.eq(parts[1].leader, "/*")
        t.eq(parts[1].flags.start, true)
        t.eq(parts[1].flags.offset, 1)
        t.eq(parts[2].flags.middle, true)
        t.eq(parts[2].flags.requires_blank, true)
        t.eq(parts[3].flags.ending, true)
        t.eq(parts[3].flags.allow_x_end, true)
    end)

    t.test("a negative offset keeps its sign", function()
        t.eq(bc._parse_format_comments("s-1:/*")[1].flags.offset, -1)
    end)

    t.test("a line comment marker matches leader, padding and text", function()
        local pattern = bc._comment_pattern(bc._parse_format_comments(":--")[1], "!")
        local padding, text = ("-- ! bang"):match(pattern)
        t.eq(padding, "-- ")
        t.eq(text, "! bang")
    end)

    t.test("a marker matches at the end of a line of code", function()
        local pattern = bc._comment_pattern(bc._parse_format_comments(":--")[1], "!")
        local padding, text = ("local x = 1 -- ! note"):match(pattern)
        t.eq(padding, " -- ")
        t.eq(text, "! note")
    end)

    t.test("an unmarked comment does not match", function()
        local pattern = bc._comment_pattern(bc._parse_format_comments(":--")[1], "!")
        t.is_nil(("-- plain"):match(pattern))
    end)

    t.test("a marker with pattern-special characters is escaped", function()
        local pattern = bc._comment_pattern(bc._parse_format_comments(":#")[1], "?")
        local _, text = ("# ? why"):match(pattern)
        t.eq(text, "? why")
    end)
end)
